import React, { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import DashboardPanel from '../../components/dashboard/DashboardPanel.jsx';
import MobileDashboardNav from '../../components/layouts/MobileDashboardNav.jsx';
import Sidebar from '../../components/layouts/Sidebar.jsx';
import Button from '../../components/ui/Button.jsx';
import { formatUser, mapAssignment, uniqueAssignments, uniqueTasks } from '../../utils/dataMappers.js';
import { getApiErrorMessage, getAssignments, getTasks } from '../../services/api.js';
import { clearSession, getSession } from '../../utils/authSession.js';

const styles = { Pending: 'bg-amber-100 text-amber-800', 'In Progress': 'bg-blue-100 text-blue-800', Review: 'bg-purple-100 text-purple-800', Completed: 'bg-emerald-100 text-emerald-800' };
function healthMessage(value) { if (value < 35) return 'Every small step counts — choose one task to start today.'; if (value < 70) return 'Nice momentum. Keep turning active work into reviews.'; return 'Excellent progress — your workspace is in great shape!'; }

function WorkspacePage() {
  const navigate = useNavigate(); const user = formatUser(getSession()?.user);
  const [assignments, setAssignments] = useState([]); const [notice, setNotice] = useState(''); const [loading, setLoading] = useState(true);
  useEffect(() => { (async () => { try { const [assignmentResponse, taskResponse] = await Promise.all([getAssignments(), getTasks()]); const tasks = uniqueTasks(taskResponse.data); setAssignments(uniqueAssignments(assignmentResponse.data).map((assignment) => mapAssignment(assignment, tasks))); } catch (error) { setNotice(getApiErrorMessage(error, 'Could not load workspace data.')); } finally { setLoading(false); } })(); }, []);
  const average = useMemo(() => assignments.length ? Math.round(assignments.reduce((sum, item) => sum + item.progress, 0) / assignments.length) : 0, [assignments]);
  function logout() { clearSession(); navigate('/'); }
  return <div className="min-h-screen bg-[#f5f7fb] lg:flex"><Sidebar user={user} onLogout={logout}/><main className="min-w-0 flex-1"><header className="border-b border-slate-200 bg-white"><div className="flex min-h-16 items-center justify-between px-4 sm:px-6 lg:px-8"><div><p className="text-xs font-black uppercase tracking-widest text-[#139f98]">Workshop</p><h1 className="text-xl font-black">Project Workspace</h1></div><Button to="/dashboard" variant="secondary">Dashboard</Button></div><MobileDashboardNav/></header><div className="px-4 py-6 sm:px-6 lg:px-8">{notice && <div role="alert" className="mb-5 rounded-lg border border-red-200 bg-red-50 p-3 text-sm font-bold text-red-800">{notice}</div>}{loading ? <p className="rounded-lg bg-white p-4 font-semibold text-slate-500">Loading workspace…</p> : <div className="grid gap-6 xl:grid-cols-[1.4fr_.8fr]"><DashboardPanel title="Assignments" action={`${assignments.length} visible`}><p className="mb-4 text-sm text-slate-500">Assignment creation happens in each group’s Leader panel.</p><div className="grid gap-3">{assignments.map((item) => <button key={item.id} type="button" onClick={() => navigate(`/groups/${item.groupworkId}`)} className="rounded-lg border border-slate-200 p-4 text-left hover:border-[#073ca6]"><div className="flex justify-between gap-3"><div><h2 className="font-black">{item.title}</h2><p className="text-sm text-slate-500">{item.group}</p></div><span className={`h-fit rounded px-2 py-1 text-xs font-black ${styles[item.status] || 'bg-slate-100'}`}>{item.status}</span></div><div className="mt-3 h-2 overflow-hidden rounded bg-slate-100"><div className="h-full bg-[#139f98]" style={{width:`${item.progress}%`}}/></div></button>)}{!assignments.length && <p className="text-sm font-semibold text-slate-500">No assignments are available to you.</p>}</div></DashboardPanel><div className="grid gap-6"><DashboardPanel title="Workspace Health" action={`${average}% avg`}><div className="h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-[#073ca6]" style={{width:`${average}%`}}/></div><p className="mt-4 text-sm font-bold text-slate-700">{healthMessage(average)}</p></DashboardPanel><DashboardPanel title="How to work here"><p className="text-sm leading-6 text-slate-600">Open your group to view details, submit work, or—if you are the leader—manage assignments and members.</p></DashboardPanel></div></div>}</div></main></div>;
}
export default WorkspacePage;
